### ISSUE TITLE
Barometric altitude, Bluetooth

### ISSUE THREAD

**Issue by saleweaver** [flysight/flysight-2-firmware#12]
Hi, thanks a lot for the great device!

Wouldn't it be a good idea to take elevation from the barometric sensor instead of gps? Would likely introduce the need to start the device on the ground, but could it be an add-on? 

Do you have plans to support Bluetooth connectivity? The hardware seems to be there. 

I've developed quite some Multiplattform apps with esp32 devices and BLE, I think there's a lot of functionality that can be  added given the hardware choices. 😄

Cheers and merry Christmas 
Michael

**Comment by crwper** [comment]
What use case do you have in mind for barometric altitude?

Bluetooth development is already underway--the initial "draft" is in the `master` branch here. Currently, this includes a couple of services: one for file access (to data download, configuration, and firmware update) and one for live GNSS data (position and velocity). What else would you like to see supported?

**Comment by saleweaver** [comment]
Sorry for the late response, didn't see you responded... 

The barometric altitude was interesting as a talking altimeter, but I think leaving this to a device that's especially made for this makes sense. 

As per bluetooth, that's pretty much it. Sounds really good.

**Comment by saleweaver** [comment]
Another question - do you have documentation for the SENSOR.csv file?

I've tried to wrap my head around the time field of $DATA entries- thinking it would maybe be gps tow. I don't get to the correct dates though, calculating them for gps tow is off by 8 days. I'm either doing something wrong with gps tow, or it's not gps tow...

**Comment by crwper** [comment]
Time for the sensor entries is "system time" in milliseconds--just the number of milliseconds since the last reset measured using the system clock. To sync this up with GNSS data, you need to use the `$TIME` messages. These are generated every time the GNSS receiver puts out a time pulse, and record the system time of that time pulse as well as the UTC week number and time of week for the time pulse reported by the GNSS receiver.

**Comment by saleweaver** [comment]
Thought so... 

I'm trying to match data between my insta360 sensor data and the flysight, I'm working on a video overlay for the data. Given the insta360 data, I can get a pretty exact exit timing at 5:47.5.. or 347.5 seconds (which is the elapsed time since start of recording, combined with the creation time of the video I get an exact timestamp for the exit). 

![plot](https://github.com/flysight/flysight-2-firmware/assets/50274907/85f0b7d5-5ba3-4093-827f-a226c3262bb2)

Combining this with the data from the flysight, thanks to your explanation about time and $TIME values, I can match it to the flysight: 

![plot_fly](https://github.com/flysight/flysight-2-firmware/assets/50274907/d3dab957-555a-4aa5-b6fc-29e28989d36b)


From your experience, is there a better way to determine the exit from flysight data?

**Comment by crwper** [comment]
I think you've got accelerometer and gyro reversed. In the `$IMU` message, `ax`, `ay`, and `az` are the accelerometer components in g, and `wx`, `wy`, and `wz` are gyro components in deg/s.

I haven't taken a closer look at the additional sensor data for exit, but historically, for skydives, horizontal velocity is the easiest way to nail down exit, as it takes a very sharp turn downward at the moment of exit in almost every jump I've looked at.

Another thing which may be helpful for you in syncing the data is that the light flashes off exactly when each time pulse is received (i.e., at every `$TIME` message). So if you video the light when it's flashing, and you can get it synchronized within a second using other methods, this should give you a very precise sync.

**Comment by saleweaver** [comment]
I'll check it, I think I have it in fact reversed... Have been looking through data for too long today. 😄

I'll also have a look at the horizontal speed, that sounds promising. I'm mainly interested in wingsuit exits/flying, but the deceleration will be true there too. Might be easier. 

The app is supposed to be free to use for everyone, and the goal is to have the syncing fully automated. That will make relying on the light harder. I've also tried to train a model on exits and analyze the video using AI, but that'll be too expensive for a free app, although it was fun waisting my time on it 😂. 

Thanks a lot for the recommendations!
