### ISSUE TITLE
State of bluetooth

### ISSUE THREAD

**Issue by gismya** [flysight/flysight-2-firmware#32]
Hello!

Has there been any progress on the Bluetooth functionality? I've been looking at making a mobile application to easily fetch key values without having to connect to a computer between jumps, initially for speed skydiving. I see there's some movement within the branches, and I figured an open question here was a better way of asking than in a private email - in case other people are wondering the same thing.

**Comment by crwper** [comment]
There's been a lot of progress. I would say the basic Bluetooth interface is nearly complete, and there are example applications written in Python and (in progress) iOS which demonstrate the features. At the moment, most development discussions are on the developer Discord. For now, please send me an email (michael@flysight.ca) if you'd like an invite to the Discord.

**Comment by gismya** [comment]
Great to hear. I've sent you the email! Thank you.
